set number
syntax on
set ignorecase
set incsearch
set wildmenu
set softtabstop=4
set shiftwidth=4
set expandtab
set autoindent
set laststatus=2
set mouse=a
colorscheme desert
set backupdir-=.
set backupdir^=~/tmp,/tmp
